const fs = require('fs');
const path = require('path');

const soundsDir = path.join(__dirname, 'assets', 'sounds');
const outputFile = path.join(__dirname, 'assets', 'sound_manifest.js');

const manifest = {};

if (!fs.existsSync(soundsDir)) {
    console.error(`Directory not found: ${soundsDir}`);
    process.exit(1);
}

const packs = fs.readdirSync(soundsDir).filter(f => fs.statSync(path.join(soundsDir, f)).isDirectory());

packs.forEach(pack => {
    const packDir = path.join(soundsDir, pack);
    const files = fs.readdirSync(packDir).filter(f => f.endsWith('.wav'));

    // Initialize pack config
    manifest[pack] = {
        id: pack,
        files: files.length, // Total count (fallback)
        standard: [],
        space: [],
        enter: []
    };

    files.forEach(file => {
        if (file.includes('space')) {
            manifest[pack].space.push(file);
        } else if (file.includes('enter')) {
            manifest[pack].enter.push(file);
        } else {
            manifest[pack].standard.push(file);
        }
    });

    // Cleanup for cleaner JSON
    manifest[pack].space_count = manifest[pack].space.length;
    manifest[pack].enter_count = manifest[pack].enter.length;
    manifest[pack].standard_count = manifest[pack].standard.length;
});

const content = `// This file is auto-generated by generate_manifest.js
// Run 'node generate_manifest.js' after adding/removing sounds.
const SOUND_MANIFEST = ${JSON.stringify(manifest, null, 4)};
`;

fs.writeFileSync(outputFile, content);
console.log(`Manifest generated at ${outputFile}`);
console.log(manifest);
